Repository GoogleCloudPlatform/khi, pull requests merged in 2025-06, with the labels that each got.

#192 bugfix: Fix panic on container log parser
  pkg/source/gcp/task/gke/k8s_container/parser.go
  pkg/source/gcp/task/gke/k8s_container/parser_test.go
  pkg/task/runner.go
Labels: bug, backend:parser

#190 Update README and docs/en directory structure
  README.ja.md
  README.md
  docs/en/development-contribution/contributing.md
  docs/en/development-contribution/development-guide.md
  docs/en/setup-guide/oss-kubernetes-clusters.md
  docs/en/tutorial/getting-started.md
  docs/en/visualization-guide/user-guide.md
  docs/ja/development-contribution/development-guide.md
  docs/ja/setup-guide/oss-kubernetes-clusters.md
  docs/ja/visualization-guide/user-guide.md
Labels: documentation

#112 Adding document about KHI task system
  docs/en/images/inspection-task-structure.png
  docs/en/khi-task-system-concept.md
Labels: documentation

#197 Add progress reporting feature during loading jsonl file
  pkg/inspection/metadata/progress/progress_util.go
  pkg/inspection/metadata/progress/progress_util_test.go
  pkg/source/oss/parser/logfile-reader.go
Labels: bug, backend:parser

#201 Standardize Task Package Structure to Resolve Initialization Order Issues
  docs/en/khi-task-system-concept.md
  pkg/inspection/task/label.go
  pkg/task/task.go
Labels: bug, documentation, backend:core

#208 Fix the warning of @angular-eslint/prefer-inject lint
  web/.eslintrc.json
  web/src/app/annotator/common-field-annotator.component.ts
  web/src/app/app.route.guard.spec.ts
  web/src/app/common/resolve-text.pipe.ts
  web/src/app/common/timestamp-format.pipe.spec.ts
  web/src/app/common/timestamp-format.pipe.ts
  web/src/app/dialogs/inspection-metadata/inspection-metadata.component.ts
  web/src/app/dialogs/new-inspection/new-inspection.component.ts
  web/src/app/dialogs/progress/progress.component.ts
  web/src/app/dialogs/request-user-action-popup/request-user-action-popup.component.ts
  web/src/app/dialogs/startup/startup.component.ts
  web/src/app/diff/diff-view.component.ts
  web/src/app/extensions/extension-common/extension.ts
  web/src/app/header/graph-menu.component.ts
  web/src/app/header/main-menu.component.ts
  web/src/app/header/titlebar.component.ts
  web/src/app/header/toolbar.component.ts
  web/src/app/log/header.component.ts
  web/src/app/log/log-view.component.ts
  web/src/app/pages/diff/diff.component.ts
  web/src/app/pages/graph/architecture-graph/architecture-graph.component.ts
  web/src/app/pages/main/main.component.ts
  web/src/app/root.module.ts
  web/src/app/services/api/backend-api.service.spec.ts
  web/src/app/services/api/backend-api.service.ts
  web/src/app/services/api/backend-connection.service.ts
  web/src/app/services/data-loader.service.ts
  web/src/app/services/frame-connection/frames/diff-page-datasource-server.service.ts
  web/src/app/services/frame-connection/frames/diff-page-datasource.service.ts
  web/src/app/services/frame-connection/frames/graph-page-datasource-server.service.ts
  web/src/app/services/frame-connection/frames/graph-page-datasource.service.ts
  web/src/app/services/frame-connection/window-connector.service.spec.ts
  web/src/app/services/frame-connection/window-connector.service.ts
  web/src/app/services/graph-converter.service.ts
  web/src/app/services/popup/popup-manager-impl.ts
  web/src/app/services/progress/progress-dialog.service.ts
  web/src/app/services/selection-manager.service.ts
  web/src/app/services/timeline-selection.service.ts
  web/src/app/services/title-strategy.service.ts
  web/src/app/timeline/CanvasKeyEventHandler.ts
  web/src/app/timeline/TimelineScrollStrategy.ts
  web/src/app/timeline/canvas/timeline_renderer.service.ts
  web/src/app/timeline/timeline.component.ts
Labels: frontend, clean up
