Repository GoogleCloudPlatform/khi, pull requests merged in 2025-02, with the labels that each got.

#50 Add warning callout not to expose KHI port on the internet
  README.ja.md
  README.md
Labels: documentation

#49 Add security policy to KHI.
  SECURITY.md
Labels: documentation

#52 Add development guide
  README.ja.md
  README.md
  docs/contributing.md
  docs/en/development-guide.md
  scripts/make/testing.mk
Labels: documentation

#48 Add instruction around `DATA_WRITE` audit log.
  README.ja.md
  README.md
Labels: documentation

#68 Fixed the race condition issue on form fields(fix #64)
  pkg/inspection/form/textform.go
  pkg/inspection/form/textform_test.go
  pkg/inspection/metadata/form/conformance_test.go
  pkg/inspection/metadata/form/form.go
  pkg/inspection/metadata/form/form_test.go
  pkg/source/gcp/task/form_test.go
  pkg/testutil/form/util.go
Labels: bug

#71 fix: annotator issues on frontend
  web/src/app/annotator/common-field-annotator.component.ts
  web/src/app/annotator/log/default.ts
  web/src/app/annotator/log/resource-reference-list.component.html
  web/src/app/annotator/log/resource-reference-list.component.sass
  web/src/app/annotator/log/resource-reference-list.component.ts
  web/src/app/annotator/timeline/resolver.ts
  web/src/app/common/schema/inter-window-messages.ts
  web/src/app/diff/diff-view.component.ts
  web/src/app/extensions/extension-common/extension-store.ts
  web/src/app/extensions/extension-common/extension-types/timeline-navigator.ts
  web/src/app/extensions/public/timeline-navigator-extensions.ts
  web/src/app/log/header.component.ts
  web/src/app/log/log-view.component.ts
  web/src/app/pages/diff/diff.component.ts
  web/src/app/services/data-loader.service.ts
  web/src/app/services/filter/timeline-filter-chain.spec.ts
  web/src/app/services/filter/timeline-filter-chain.ts
  web/src/app/services/frame-connection/frames/diff-page-datasource.service.ts
  web/src/app/services/graph-converter.service.ts
  web/src/app/services/inspection-data-store.service.ts
  web/src/app/services/selection-manager.service.ts
  web/src/app/services/timeline-filter.spec.ts
  web/src/app/store/inspection-data.ts
  web/src/app/store/log.ts
  web/src/app/store/timeline-filter.spec.ts
  web/src/app/store/timeline-filter.ts
  web/src/app/store/timeline.spec.ts
  web/src/app/store/timeline.ts
  web/src/app/timeline/CanvasKeyEventHandler.ts
  web/src/app/timeline/TimelineScrollStrategy.ts
  web/src/app/timeline/background-canvas.ts
  web/src/app/timeline/canvas/timeline_gl_row_renderer.ts
  web/src/app/timeline/canvas/timeline_renderer.service.ts
  web/src/app/timeline/canvas/types.ts
  web/src/app/timeline/navigator/navigator.component.ts
  web/src/app/timeline/timeline.component.ts
  web/src/app/timeline/timeline.component.vm.ts
  web/src/app/utils/timeline-collection-util.spec.ts
  web/src/app/utils/timeline-collection-util.ts
Labels: enhancement

#73 Adding types to store uploaded files
  pkg/server/upload/store.go
  pkg/server/upload/store_test.go
  pkg/server/upload/storeprovider.go
  pkg/server/upload/storeprovider_test.go
  pkg/server/upload/uploadtoken.go
  pkg/server/upload/verifier.go
  pkg/server/upload/verifier_test.go
Labels: enhancement

#70 chore: Fixes several minor problems around devops
  .github/workflows/pr-request.yaml
  scripts/pre-commit
Labels: enhancement
